"""trade_flows_and_ingestion_runs

Revision ID: 13811bc834fe
Revises: 9ce05823f7a8
Create Date: 2026-04-12 20:18:52.178307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13811bc834fe'
down_revision: Union[str, None] = '9ce05823f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_hint', sa.String(length=128), nullable=True),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('revised_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('trade_flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=128), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('reporter_country', sa.String(length=8), nullable=False),
    sa.Column('partner_country', sa.String(length=32), nullable=False),
    sa.Column('commodity', sa.String(length=128), nullable=False),
    sa.Column('flow_direction', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('quantity_unit', sa.String(length=64), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eia_origin_id', sa.String(length=64), nullable=True),
    sa.Column('eia_destination_id', sa.String(length=64), nullable=True),
    sa.Column('eia_grade_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'dataset', 'period_date', 'reporter_country', 'partner_country', 'commodity', 'flow_direction', name='uq_trade_flow_business_key')
    )
    op.create_table('trade_flow_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_flow_id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_quantity', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('previous_quantity_unit', sa.String(length=64), nullable=True),
    sa.Column('previous_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_quantity', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('new_quantity_unit', sa.String(length=64), nullable=True),
    sa.Column('new_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_flow_id'], ['trade_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_flow_revisions_ingestion_run_id'), 'trade_flow_revisions', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_trade_flow_revisions_trade_flow_id'), 'trade_flow_revisions', ['trade_flow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_flow_revisions_trade_flow_id'), table_name='trade_flow_revisions')
    op.drop_index(op.f('ix_trade_flow_revisions_ingestion_run_id'), table_name='trade_flow_revisions')
    op.drop_table('trade_flow_revisions')
    op.drop_table('trade_flows')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
