"""data_quality_schema_fingerprints

Revision ID: b4bb1e3f2505
Revises: a1b2c3d4e5f6
Create Date: 2026-04-12 21:36:18.469789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bb1e3f2505'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_fingerprints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=128), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('columns_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'dataset', name='uq_schema_fingerprint_source_dataset')
    )
    op.create_index(op.f('ix_schema_fingerprints_dataset'), 'schema_fingerprints', ['dataset'], unique=False)
    op.create_index(op.f('ix_schema_fingerprints_source'), 'schema_fingerprints', ['source'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=128), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_dataset'), 'data_quality_issues', ['dataset'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_ingestion_run_id'), 'data_quality_issues', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_issue_type'), 'data_quality_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_severity'), 'data_quality_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_source'), 'data_quality_issues', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_quality_issues_source'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_severity'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_issue_type'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_ingestion_run_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_dataset'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_schema_fingerprints_source'), table_name='schema_fingerprints')
    op.drop_index(op.f('ix_schema_fingerprints_dataset'), table_name='schema_fingerprints')
    op.drop_table('schema_fingerprints')
    # ### end Alembic commands ###
